tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'archey'
brew 'ffmpeg'
brew 'fastlane'
brew 'fzf'
brew 'ghi'
brew 'gh'
brew 'git'
brew 'git-extras'
brew 'imagemagick'
brew 'imageoptim-cli'
brew 'mas'
brew 'nvm'
brew 'python'
brew 'tig'
brew 'tree'
brew 'watchman'
brew 'yarn'
brew 'youtube-dl'
brew 'z'

cask 'alfred'
cask 'dash'
cask 'discord'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'flux'
cask 'github'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
cask 'ndm'
cask 'notion'
cask 'react-native-debugger'
cask 'screaming-frog-seo-spider'
cask 'setapp'
cask 'spotify'
cask 'sublime-text'
cask 'tunnelbear'
cask 'visual-studio-code'
cask 'visual-studio-insiders'
cask 'vlc'
cask 'zoomus'


# Android React Native Development
# Use JAVA 8 which is the stablest version for Android.
# https://stackoverflow.com/questions/53059771/could-not-determine-java-version-from-11-0-1-when-running-npm-run-android

cask 'adoptopenjdk8'
# https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106
# until the fix you can run
# brew cask install adoptopenjdk/openjdk/adoptopenjdk8

brew 'gradle'
cask 'android-file-transfer'
cask 'android-platform-tools'
cask 'android-sdk'
cask 'android-studio'
