tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'archey'
brew 'bat'
brew 'ffmpeg'
brew 'fastlane'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-extras'
brew 'imagemagick'
brew 'imageoptim-cli'
brew 'mas'
brew 'nvm'
brew 'python'
brew 'tig'
brew 'tree'
brew 'watchman'
brew 'yarn'
brew 'youtube-dl'
brew 'z'

cask 'alfred'
cask 'dash'
cask 'discord'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'flipper'
cask 'flux'
cask 'github'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
cask 'ndm'
cask 'notion'
cask 'rectangle-pro'
cask 'react-native-debugger'
cask 'screaming-frog-seo-spider'
cask 'setapp'
cask 'spotify'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'visual-studio-insiders'
cask 'vlc'
cask 'zoomus'


# React Native Development Setup for Android

# The Zulu OpenJDK distribution offers JDKs for both Intel and M1 Macs.
# This will make sure your build are faster on M1 Macs compared to using an Intel-based JDK.
# https://reactnative.dev/docs/environment-setup#installing-dependencies
cask 'zulu11'

brew 'gradle'
cask 'android-file-transfer'
cask 'android-platform-tools'
cask 'android-sdk'
cask 'android-studio'
