#!/usr/bin/env bash

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'archey4'
brew 'bat'
brew 'ffmpeg'
brew 'fzf'
brew 'jq'
brew 'gh'
brew 'git'
brew 'git-extras'
brew 'imagemagick'
brew 'imageoptim-cli'
brew 'nvm'
brew 'python'
brew 'tree'
brew 'youtube-dl'
brew 'z'

# React Native Development Setup
tap 'facebook/fb'
brew 'idb-companion' # automating iOS simulators and devices

brew 'ios-deploy'
brew 'expo-orbit'
brew 'fastlane'
brew 'mas' # Mac App Store command line interface
brew 'watchman'

# Other Stuff
# cask 'alfred'
cask 'arc'
cask '1password'
cask 'around'
cask 'brave-browser'
cask 'discord'
cask 'dropbox'
cask 'elgato-wave-link'
cask 'figma'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
# cask 'microsoft-teams'
cask 'notion'
# cask 'rectangle-pro'
cask 'screaming-frog-seo-spider'
cask 'setapp'
cask 'obs'
cask 'raycast'
cask 'stremio'
cask 'spotify'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'visual-studio-code-insiders'
cask 'vlc'
cask 'zoom'